#!/bin/bash

templatefile="./mediainfo_template"
crawldir="/Users/pozar/Desktop/tosort/Tims_Phone_Pix/Camera"

grep -v ^# $templatefile | grep \; | xargs echo -n | sed 's/% %/	/g' | sed 's/% /	/g' | sed 's/%//g'

# Start to crawl the directory and feed it to mediainfo...
find $crawldir -type f | grep -i \.mp4 | while read mediafile;do
mediainfo --inform="file://$templatefile" $mediafile
done

